orderio/chat/urls.py
from django.urls import path
from chat import views
app_name = "chat"
urlpatterns = [
    path("",views.index,name="index"),
    path("draft",views.draft,name="draft"),
    path("read_message/<int:pk>",views.read_message,name="read_message"),
    path("create_thread/<int:pk>",views.create_thread,name="create_thread")
]

orderio/meal/urls.py
from django.urls import path
from . import views
app_name = "meal"
urlpatterns = [
    path("create_meal",views.create_meal,name="create_meal"),
    path("update_meal/<int:pk>",views.update_meal,name="update_meal"),
    path("delete_meal/<int:pk>",views.delete_meal,name="delete_meal"),
    path("<int:pk>",views.view_meal,name="view_meal"),
    path("all_meals",views.all_meals,name="all_meals"),
    
    path("create_category",views.create_category,name="create_category"),
    path("update_category/<int:pk>",views.update_category,name="update_category"),
    path("delete_category/<int:pk>",views.delete_category,name="delete_category"),
    path("category/<int:pk>",views.view_category,name="view_category"),
    path("all_categories",views.all_categories,name="all_categories"),
]

orderio/orderio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from main.views import handle_not_found
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace="main")),
    path('manager/', include('manager.urls',namespace="manager")),
    path('employee/', include('employee.urls',namespace="employee")),
    path('account/', include('account.urls')),
    path('order/', include('order.urls',namespace="order")),
    path('menu/', include('menu.urls',namespace="menu")),
    path('meal/', include('meal.urls',namespace="meal")),
    path('notification/', include('notification.urls',namespace="notification")),
    path('chat/', include('chat.urls',namespace="chat")),
]
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'main.views.handle_not_found'

orderio/meal/models.py
from django.db import models
from django.urls import reverse
from main.images_rename import img_path
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50,blank=True,null=True)
    description = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("meal:view_category", kwargs={"pk": self.pk})
    
    
class Meal(models.Model):
    #realtionships    
    category =models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    #attributes
    name = models.CharField(max_length=100,blank=True)
    price = models.DecimalField(max_digits=6,decimal_places=2,default=0)
    description = models.TextField(blank=True,null=True)
    calories = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    meal_img = models.ImageField(null=True,default="meal-default.png",upload_to=img_path)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("meal:view_meal", kwargs={"pk": self.pk})

orderio/meal/forms.py
from django.contrib.auth import forms
from django.forms import ModelForm,CharField,DecimalField
from .models import Category,Meal
from django.core.validators import RegexValidator

class CategoryForm(ModelForm):
    name = CharField(required=True)
    class Meta():
        
        model = Category
        fields = ('name','description')
        exclude = []
        labels = {
            "name":"Enter Category Name",
            "description":"Enter description",
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Category Name*'})
        self.fields['description'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Category Description'})
    
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if self.instance.pk is None:
            if Category.objects.filter(name=name):
                raise forms.ValidationError("This category name already exists!",code="Exists!")
        if len(name)>50:
            raise forms.ValidationError("The Category name is too long. Maximum 50 characters!")
        return name
    
    def clean_description(self):
        description = self.cleaned_data.get("description")
        if len(description)>1024:
            raise forms.ValidationError("The Category description is too long. Maximum 1024 characters!")
        return description
    
class MealForm(ModelForm):
    name = CharField(required=True)
    price = DecimalField(required=True)
    class Meta():
        model = Meal
        fields = "__all__"
        exclude = []
        labels = {
            "name":"Meal Name*",
            "description":"Meal Description",
            "price" : "Meal Price*",
            "calories" : "Total Calories",
            "meal_img" : "Image"
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Meal Name*'})
        self.fields['description'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Meal Description'})
        self.fields['calories'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Meal Calories'})
        self.fields['price'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Meal Price*'})
        self.fields['meal_img'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Meal Image'})
        self.fields['category'].widget.attrs.update({'class': 'form-control form-control-user','placeholder':'Meal Category*'})
    
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if self.instance.pk is None:
            if Meal.objects.filter(name=name):
                raise forms.ValidationError("This Meal name already exists!",code="Exists!")
        if len(name)>50:
            raise forms.ValidationError("The Meal name is too long. Maximum 50 characters!")
        return name
    
    def clean_price(self):
        price = self.cleaned_data.get("price")
        if float(price) <=0:          
            raise forms.ValidationError("The meal price is incorrect!",code="Incorrect!")
        return price
    
    def clean_description(self):
        description = self.cleaned_data.get("description")
        if len(description)>2048:
            raise forms.ValidationError("The Meal description is too long. Maximum 1024 characters!")
        return description

orderio/meal/views.py
from django.shortcuts import get_object_or_404, render,redirect
from meal.models import Meal,Category
from django.contrib import messages
from main.decorators import allowed_users
from django.contrib.auth.decorators import login_required
from .forms import CategoryForm,MealForm
# Create your views here.


@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def create_meal(request):
    form = MealForm()
    if request.method == 'POST':
        form = MealForm(request.POST,request.FILES,)
        if form.is_valid():
            messages.success(request,f"Meal {request.POST.get('name')} was created successfully!")
            form.save()
            return redirect("meal:create_meal")
            
    context = {"form":form}
    return render(request,"meal/create_meal.html",context)

def view_meal(request,pk):
    meal = get_object_or_404(Meal,pk=pk)
    context = {"meal":meal}
    return render(request,"meal/view_meal.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def all_meals(request):
    meals = Meal.objects.all()
    context = {"meals":meals}
    return render(request,"meal/all_meals.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def update_meal(request,pk):
    meal = get_object_or_404(Meal,pk=pk)
    form = MealForm(instance=meal)
    if request.method == 'POST':
        form = MealForm(request.POST,request.FILES,instance=meal)
        if form.is_valid():
            messages.success(request,f"Meal {request.POST.get('name')} was updated successfully!")
            form.save()
            return redirect("meal:all_meals")
    context = {"form":form}
    return render(request,"meal/update_meal.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def delete_meal(request,pk):
    meal = get_object_or_404(Meal,pk=pk)
    meal.delete()
    messages.success(request,"The meal was deleted successfully!")
    return redirect("meal:all_meals")

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def create_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            messages.success(request,f"Category {request.POST.get('name')} was created successfully!")
            form.save()
            return redirect("meal:all_categories")
    context = {"form":form}
    return render(request,"meal/create_category.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def view_category(request,pk):
    category = get_object_or_404(Category,pk=pk)
    context = {"category":category}
    return render(request,"meal/view_category.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def all_categories(request):
    categories = Category.objects.all()
    context = {"categories":categories}
    return render(request,"meal/all_categories.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def update_category(request,pk):
    category = get_object_or_404(Category,pk=pk)
    form = CategoryForm(instance=category)
    if request.method == 'POST':
        form = CategoryForm(request.POST,instance=category)
        if form.is_valid():
            messages.success(request,f"Category {request.POST.get('name')} was updated successfully!")
            form.save()
            return redirect("meal:all_categories")
    context = {"form":form}
    return render(request,"meal/update_category.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def delete_category(request,pk):
    category = get_object_or_404(Category,pk=pk)
    category.delete()
    messages.success(request,"Category was deleted successfully!")
    return redirect("meal:all_categories")

orderio/templates/meal/all_categories.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
Category List
{% endblock title %}
{% block content %}

<!-- Custom styles for this page -->

{% for message in messages %}
<div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
 <!-- Page Heading -->
 <div class="container-fluid">
 <h1 class="h3 mb-2 text-gray-800">Category List</h1>
 <p class="mb-4">Click on the category name to view more details.</p>

 <div class="card shadow mb-4">
     <div class="card-header py-3">
         <h6 class="m-0 font-weight-bold text-primary">Category List</h6>
     </div>
     <div class="card-body">
         <div class="table-responsive">
             <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                 <thead>
                     <tr>
                      
                      <th>Category Name</th>
                      <th>Description</th>
                      <th>Action</th>
                     </tr>
                 </thead>
                 <tfoot>
                  <tr>
                   
                    <th>Category Name</th>
                    <th>Description</th>
                    <th>Action</th>
                  </tr>
                </tfoot>
                 <tbody>
                  {% for category in categories %}
                   <tr>
                     
                     <td><a href="{{category.get_absolute_url}}">{{category.name}}</a> </td>
                     <td>{{category.description|truncatechars:40}}</td>
                     <td>
                      <a href="{% url 'meal:update_category' category.id %}" class="btn btn-sm btn-info">Edit</a>  
                      <button data-url="{% url 'meal:delete_category' category.id %}" value="{% url 'meal:delete_category' category.id %}" data-bs-toggle="modal" data-bs-target="#exampleModal"
                      class="btn btn-sm btn-danger" id="del-btn{{category.pk}}">Delete</button> </td>
                   </tr>
                   {% endfor %}

                 </tbody>
             </table>
         </div>
     </div>
 </div>

</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">You are about to delete a meal!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to <b class="text-danger">delete</b> this meal?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="conf-btn">Delete</button>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/danger-confirmation.js' %}"></script>

{% endblock content %}

orderio/templates/meal/all_meals.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
  Meal List
{% endblock title %}
{% block content %}

<!-- Custom styles for this page -->

{% for message in messages %}
<div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
 <!-- Page Heading -->
 <div class="container-fluid">
 <h1 class="h3 mb-2 text-gray-800">Meal List</h1>
 <p class="mb-4">Click on the meal name to view more details.</p>

 <div class="card shadow mb-4">
     <div class="card-header py-3">
         <h6 class="m-0 font-weight-bold text-primary">Meal List</h6>
     </div>
     <div class="card-body">
         <div class="table-responsive">
             <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                 <thead>
                     <tr>
                       <th>Image</th>
                      <th>Meal Name</th>
                      <th>Description</th>
                      <th>Category</th>
                      <th>Action</th>
                     </tr>
                 </thead>
                 <tfoot>
                  <tr>
                    <th>Image</th>
                    <th>Meal Name</th>
                    <th>Description</th>
                    <th>Action</th>
                  </tr>
                </tfoot>
                 <tbody>
                  {% for meal in meals %}
                   <tr>
                     <td> <img src="{{meal.meal_img.url}}" class="img-thumbnai" width="50px" height="50px" alt=""></td>
                     <td><a href="{{meal.get_absolute_url}}" >{{meal.name|truncatechars:20}}</a> </td>
                     <td>{{meal.description|truncatechars:40}}</td>
                     <td>{{meal.category.name|truncatechars:40}}</td>
                     <td>
                      <a href="{% url 'meal:update_meal' meal.id %}" class="btn btn-sm btn-info">Edit</a>  
                      <button data-url="{% url 'meal:delete_meal' meal.id %}" value="{% url 'meal:delete_meal' meal.id %}" data-bs-toggle="modal" data-bs-target="#exampleModal"
                      class="btn btn-sm btn-danger" id="del-btn{{meal.pk}}">Delete</button> </td>
                   </tr>
                   {% endfor %}

                 </tbody>
             </table>
         </div>
     </div>
 </div>

</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">You are about to delete a meal!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to <b class="text-danger">delete</b> this meal?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="conf-btn">Delete</button>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/danger-confirmation.js' %}"></script>

{% endblock content %}

orderio/templates/meal/create_category.html
{% extends "../manager-base.html" %}
{% block title %}
New Category
{% endblock title %}
{% block content %}
<div class="container-fluid" >
    {% for message in messages %}
        <div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8 offset-md-2">
                    <div class="p-5">
                        <div class="text-center mb-4">
                            <h1 class="h4 text-gray-900 ">Add a new Category!</h1>
                            <p class="text-info">Fields marked with an asterisk (*) are required.</p>
                        </div>
                            <form method="post" action="">
                                {% csrf_token %}
                            
                            {{form.name}}<br>
                          
                            {{form.description}}<br>
                                {% if form.errors %}
                                  {% for field in form %}
                                      {% for error in field.errors %} 
                                          <div class="alert alert-danger">
                                              <strong>{{ error|escape }}</strong>
                                          </div>
                                      {% endfor %}
                                  {% endfor %}
                                {% endif %}
                                <div class="text-center">
                                    <input type="submit" value="Create Category" class="btn btn-primary btn-user btn-block">
                                </div>
                           
                            </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orderio/templates/meal/create_meal.html
{% extends "../manager-base.html" %}
{% block title %}
New Meal
{% endblock title %}
{% block content %}
<div class="container-fluid" >
    {% for message in messages %}
        <div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8 offset-md-2">
                    <div class="p-5">
                        <div class="text-center mb-4">
                            <h1 class="h4 text-gray-900 ">Add a new Meal!</h1>
                            <p class="text-info">Fields marked with an asterisk (*) are required.</p>
                        </div>
                            <form method="post" action="" enctype="multipart/form-data">
                                {% csrf_token %}
                            {{form.name}}<br>
                            {{form.description}}<br>
                            {{form.price}}<br>
                            {{form.calories.label}}<br>
                            {{form.calories}}<br>
                            {{form.meal_img.label}}<br>
                            {{form.meal_img}}<br>
                            <div class="form-group row">
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    {{form.category.label}}*:                                    {{form.category}}
                                </div>
                                <div class="col-sm-3 d-flex align-items-center">
                                    <span class="align-text-bottom"><a href="{% url 'meal:create_category' %}" ><i class="fas fa-plus"></i> Create Category</a></span>
                                </div>
                            </div>
                            
                            
                            
                                {% if form.errors %}
                                  {% for field in form %}
                                      {% for error in field.errors %} 
                                          <div class="alert alert-danger">
                                              <strong>{{ error|escape }}</strong>
                                          </div>
                                      {% endfor %}
                                  {% endfor %}
                                {% endif %}
                                <div class="text-center">
                                    <input type="submit" value="Create Meal" class="btn btn-primary btn-user btn-block">
                                </div>
                           
                            </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}

orderio/templates/meal/update_meal.html
{% extends "../manager-base.html" %}
{% block title %}
Update Meal
{% endblock title %}
{% block content %}
<div class="container-fluid" >
    <a href="{% url 'meal:all_meals' %}">Back</a>
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8 offset-md-2">
                    <div class="p-5">
                        <div class="text-center mb-4">
                            <h1 class="h4 text-gray-900 ">Update meal!</h1>
                            <p class="text-info">Press the Save button when you are done with the changes.</p>
                        </div>
                            <form method="post" action="" enctype="multipart/form-data">
                                {% csrf_token %}
                            {{form.name}}<br>
                            {{form.description}}<br>
                            {{form.price}}<br>
                            {{form.calories.label}}<br>
                            {{form.calories}}<br>
                            {{form.meal_img.label}}<br>
                            {{form.meal_img}}<br>
                            <div class="form-group row">
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    {{form.category.label}}*:                                    {{form.category}}
                                </div>
                                <div class="col-sm-3 d-flex align-items-center">
                                    <span class="align-text-bottom"><a href="{% url 'meal:create_category' %}" ><i class="fas fa-plus"></i> Create Category</a></span>
                                </div>
                            </div>
                            
                            
                            
                                {% if form.errors %}
                                  {% for field in form %}
                                      {% for error in field.errors %} 
                                          <div class="alert alert-danger">
                                              <strong>{{ error|escape }}</strong>
                                          </div>
                                      {% endfor %}
                                  {% endfor %}
                                {% endif %}
                                <div class="text-center">
                                    <input type="submit" value="Save" class="btn btn-primary btn-user btn-block">
                                </div>
                           
                            </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% for message in messages %}
        <div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
{% endfor %}


{% endblock %}

orderio/templates/meal/view_category.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
  {{category.name}}
{% endblock title %}
{% block content %}
<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-3 d-none d-lg-block align-items-center">
                        
                    </div>
                    <div class="col-lg-9 border">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">{{category.name}}</h1>
                            </div>
                                 <i><b>Description:</b></i><br>
                                 {{category.description}}
                                <hr>
                            <div class="row">
                                <div class="col-md-4">
                                    Total meals in this category:
                                    <b class="text-primary">{{category.meal_set.all.count}}</b>
                                </div>
                                
                                
                            </div>
                           
                            <hr>
                            <div class="text-center">
                                <a href="{% url 'meal:update_category' category.id %}" class="btn btn-lg btn-info">Edit</a>  
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    
    
    <!-- Bootstrap core JavaScript-->
    
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'plugins/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/main-template.min.js' %}"></script>


</body>
  
{% endblock content %}


{{category.name}}

orderio/templates/meal/view_meal.html
{% extends "../public-page.html" %}
{% load static %}
{% block title %}
  {{meal.name}}
{% endblock title %}
{% block content %}
<body class="bg-gradient-primary">

    <div class="container">
        
        <div class="card o-hidden border-0 shadow-lg my-5">
            
            <div class="card-body p-0">
                <button onclick="history.back()" class=" btn btn-primary m-3"><i class="fas fa-arrow-circle-left"></i> Go Back</button>
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-3 d-none d-lg-block align-items-center my-auto">
                        <img src="{{meal.meal_img.url}}" class="img-responsive img-responsive p-2" width="100%">
                    </div>
                    <div class="col-lg-9 border">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">{{meal.name}}</h1>
                            </div>
                                 <i><b>Description:</b></i><br>
                                {{meal.description}}
                                <hr>
                            <div class="row">
                                <div class="col-md-4">
                                    Price:
                                    <b class="text-primary">${{meal.price}}</b>
                                </div>
                                <div class="col-md-4">
                                    Calories:
                                    <b class="text-primary">{{meal.calories}}</b>
                                </div>
                                <div class="col-md-4">
                                    Category:
                                    <b class="text-primary">{{meal.category.name}}</b>
                                </div>
                                
                            </div>
                           
                            <hr>
                            {% if request.user.role.name == 'manager' %}
                            <div class="text-center">
                                <a href="{% url 'meal:update_meal' meal.id %}" class="btn btn-lg btn-info">Edit</a>  
                                <a href="{% url 'meal:delete_meal' meal.id %}" class="btn btn-lg btn-info">Delete</a>  
                            </div>
                            {% endif %}
                            
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    
    
    <!-- Bootstrap core JavaScript-->
    
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'plugins/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/main-template.min.js' %}"></script>


</body>
  
{% endblock content %}