orderio/chat/urls.py
from django.urls import path
from chat import views
app_name = "chat"
urlpatterns = [
    path("",views.index,name="index"),
    path("draft",views.draft,name="draft"),
    path("read_message/<int:pk>",views.read_message,name="read_message"),
    path("create_thread/<int:pk>",views.create_thread,name="create_thread")
]

orderio/employee/urls.py
from django.urls import path
from . import views
app_name = "employee"
urlpatterns = [
    path("",views.index,name="index"),
    path("my_profile",views.my_profile,name="my_profile"),
    path("change_daily_allowance/<int:pk>",views.change_daily_allowance,name="change_daily_allowance"),
    path("daily_menu",views.daily_menu,name="daily_menu"),
    path("<int:pk>",views.employee_profile,name="employee_profile"),
    #path("delete_employee",views.delete_employee,name="delete_employee")
    #path("update_employee",views.update_employee,name="update_employee")
]

orderio/order/urls.py
from django.urls import path
from . import views
app_name = "order"
urlpatterns = [
    path("daily_orders",views.daily_orders,name="daily_orders"),
    path("create_order",views.create_order,name="create_order"),
    path("<int:pk>",views.view_order,name="view_order"),
    path("user_order_history",views.user_order_history,name="user_order_history"),
    path("delete_order/<int:pk>",views.delete_order,name="delete_order"),
    path("change_order_status/<int:pk>/<int:status>",views.change_order_status,name="change_order_status"),
    path("add_to_order",views.add_to_order,name="add_to_order"),
    path("all_orders_this_week",views.all_orders_this_week,name="all_orders_this_week"),
    path("full_order_history",views.full_order_history,name="full_order_history"),
    path("custom_order/",views.custom_order,name="custom_order")
]

orderio/orderio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from main.views import handle_not_found
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace="main")),
    path('manager/', include('manager.urls',namespace="manager")),
    path('employee/', include('employee.urls',namespace="employee")),
    path('account/', include('account.urls')),
    path('order/', include('order.urls',namespace="order")),
    path('menu/', include('menu.urls',namespace="menu")),
    path('meal/', include('meal.urls',namespace="meal")),
    path('notification/', include('notification.urls',namespace="notification")),
    path('chat/', include('chat.urls',namespace="chat")),
]
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'main.views.handle_not_found'

orderio/employee/models.py
from django.db import models
from account.models import CustomUser
from main.images_rename import img_path
from django.urls import reverse
# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=20,blank=True)

    def __str__(self):
        return self.name
class Employee(models.Model):
    #relationships
    user = models.OneToOneField(CustomUser,null=True,on_delete=models.CASCADE)
    department = models.ForeignKey(Department,on_delete=models.CASCADE,null=True)
    daily_allowance = models.DecimalField(max_digits=6,decimal_places=2,default=5)
    phone_number = models.CharField(max_length=15,blank=True,null=True)
    profile_pic = models.ImageField(null=True,default="default.png",upload_to=img_path)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
    
    def get_absolute_url(self):
        return reverse("employee:employee_profile", kwargs={"pk": self.user.pk})
    

orderio/order/models.py
from django.db import models
from employee.models import Employee
from meal.models import Meal
from menu.models import Menu
from django.urls import reverse
# Create your models here.

class Order(models.Model):
    STATUS = (
        ("Pending","Pending"),
        ("Accepted","Accepted"),
        ("Denied","Denied")
        )
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE,null=True,blank=True)
    meals = models.ManyToManyField(Meal,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    menu = models.ForeignKey(Menu,blank=True,on_delete=models.CASCADE,null=True,)
    order_status = models.CharField(default="Pending",choices=STATUS,blank=True,null=True,max_length=10)
    order_cost = models.DecimalField(max_digits=6,decimal_places=2,default=0)
    
    class Meta:
        ordering = ("-created_at",)
        
    def get_created_at_date(self):
        return self.created_at.date()
    
    def __str__(self):
        return f"{str(self.created_at.date())} {self.employee.user.username}"
    
    def get_absolute_url(self):
        return reverse("order:view_order", kwargs={"pk": self.pk})
    
    

orderio/employee/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render,get_object_or_404
from main.forms import UserProfileForm,FnameLnameForm
from main.decorators import allowed_users
from main.session_handle import Custom_Session
from django.contrib import messages
from notification.models import Notification
from menu.models import WeeklyMenu
from django.utils import timezone
from employee.employee_status import *
from employee.models import Employee
from django.http.response import HttpResponse

# Create your views here.
year = timezone.now().isocalendar().year
week = timezone.now().isocalendar().week
@login_required(login_url="login")
@allowed_users(allowed_roles=['user'])
def index(request):
    day = timezone.now().isoweekday()
    day_name = timezone.now().strftime("%A")
    has_ordered = has_order(request)
    orders = Order.objects.filter(employee = request.user.employee)[:5]
    try:
        weekly_menu = WeeklyMenu.objects.get(week=week,year=year)
        menu = weekly_menu.menu_set.get(created_for=day)
        
    except:
        menu = ""
       
    
    
    budget_available = user_money_available(request)
    context = {"budget_available":budget_available,
               "menu":menu,
               "day_name":day_name,
               "orders":orders,
               "has_ordered":has_ordered}
    return render(request,'employee/index.html',context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['user'])
def my_profile(request):
    employee = request.user.employee
    e_form = UserProfileForm(instance=employee)
    fl_form = FnameLnameForm(instance=request.user)
    if request.method == 'POST':
        e_form = UserProfileForm(request.POST,request.FILES,instance = employee)
        fl_form = FnameLnameForm(request.POST,instance=request.user)
        if e_form.is_valid() and fl_form.is_valid():
            e_form.save()
            fl_form.save()
            messages.success(request,"Profile changes were saved successfully!")
            return redirect("employee:index")
    context = {"e_form":e_form,"fl_form":fl_form}
    return render(request,'employee/employee_profile.html',context)


@login_required(login_url="login")
@allowed_users(allowed_roles=['user'])
def daily_menu(request):
    ss = Custom_Session(request)
    day = timezone.now().isoweekday()
    menu_budget = user_money_available(request)
    try:
        weekly_menu = WeeklyMenu.objects.get(week=week,year=year)
        menu = weekly_menu.menu_set.get(created_for=day)
        menu_status = "Available" if menu.allowes_orders() else "Expired"
        if not menu.approved:
            return render(request,'employee/error-template.html',{"text":f"The menu for {menu.get_day_name()} is not approved ready yet!"})
        meals = menu.meals.all()
        for meal in ss.get_menu_items():
            meals=meals.exclude(pk=meal)
        
        context={"menu":menu,"meals":meals,"day":day,"menu_status":menu_status,"menu_budget":menu_budget,"week":week,"year":year}
        return render(request,'employee/daily_menu.html',context)
    except:
        return render(request,'employee/error-template.html',{"text":f"The menu for today is not ready yet!"})

    
    
@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def change_daily_allowance(request,pk):
    employee = get_object_or_404(Employee,pk=pk)
    
    if request.method == 'POST':
        if not has_order_this_week(request,pk):
            employee.daily_allowance = request.POST.get('daily_allowance')
            employee.save()
            Notification(to_user=employee.user,from_user=request.user,text=f"Your daily allowance was changed to {float(request.POST.get('daily_allowance'))}",type=2).save()
            messages.success(request,f"Daily allowance changed for user {employee.user.username}")
        else:
            messages.warning(request,f"You cannot change the allowance for this user. Make sure the user has not placed an order yet!")
            return redirect("user_list")
    return redirect("user_list")

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def employee_profile(request,pk):
    employee = get_object_or_404(Employee,user=pk)
    
    
    context = {"employee":employee}
    return render(request,'employee/public_profile.html',context)

orderio/templates/employee/daily_menu.html
  {% extends "../user-base.html" %}
  {% load static %}
  {% block title %}
    Daily Menu
  {% endblock title %}
  {% block content %}
  <div class="container-fluid">
   
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0"><span class="float-left">Menu for: <span class="font-weight-bold text-primary">{{menu.get_day_name}}</span><br> 
          Menu status: <span class="font-weight-bold  text-{% if menu_status == 'Available' %}success{% else %}warning{% endif %}">{{menu_status}}</span></span>  
          <span class="float-right"> Your budget: <span class="fs-3 text-dark font-weight-bold">${{menu_budget}}</span></span>  </h6>
    </div>
    <div class="card-body">
      {% for message in messages %}
  <div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
      {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  <div class="row" id="main" style="min-height:70vh;">
    <div class="col-md-2 col-lg-2">
      <h1 class="h3 mb-2 text-gray-800">Today's menu</h1>
      <p class="mb-4">Here you can find the meal list for today's menu.<br>
       To view more details about the meal, click on the meal name.<br>
       To add your preferred meal, click add to order. When you are done click complete order.</p>
    </div>
    <div class="col-md-6 col-lg-7">
      <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th>Image</th>
                 <th>Meal Name</th>
                 <th>Price</th>
                 <th>Action</th>
                </tr>
            </thead>
            
            <tbody>
             {% for meal in meals %}
              <tr>
                <td> <img src="{{meal.meal_img.url}}" class="img-thumbnai" width="50px" height="50px" alt=""></td>
                <td><a href="{{meal.get_absolute_url}}" >{{meal.name|truncatechars:30}}</a> 
                  <small><br>{{meal.description|truncatechars:50}}</small>
                </td>
                <td>{{meal.price|floatformat:2}}
                  
                </td>
                <td>
                  <div class="btn-group vertical-align-middle" role="group">
                    <button value="{{meal.id}}"  id="add-btn{{meal.id}}" class="btn btn-info btn-sm ml-2" data-url="{% url 'order:add_to_order' %}">Add to Order</button>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
            </table>
    </div>
      </div>
  <div  class="col-md-4 col-lg-3 order-md-last">
    <div id="menu-items">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-primary">Your order</span>
      
      <span class="badge bg-primary rounded-pill">{% with bag|length as b %}
        {{b}}
        {% endwith %}</span>
    </h4>
    
    <ul class="list-group mb-3">
      {% for i in bag.get_menu_items.values %}
      <li class="list-group-item d-flex justify-content-between lh-sm">
        <div>
          <h6 class="my-0">{{i.name}}</h6>
          <small class="text-muted">{{i.meal_category}}</small>
        </div>
        <span class="text-muted">${{i.price}} 
          <button class="btn"  id="del-btn{{i.id}}" value="{{i.id}}" data-url="{% url 'order:add_to_order' %}">
          <i class="bi bi-x-lg text-danger"></i>
        </button></span>
        
      </li>
      {% endfor %}
      <li class="list-group-item d-flex justify-content-between">
        <span>Menu total price (USD)</span>
        <strong>${{ bag.get_total_price|floatformat:2 }}</strong>
      </li>
    </ul>

    <form class="card p-2" action="{% url 'order:create_order' %}" method="post" >
      {% csrf_token %}
      <div class="input-group">
        <input type="hidden" name="menu_id" value="{{menu.id}}">
        <button type="submit" class="btn btn-success {% if bag|length == 0 %}disabled{% endif %}">COMPLETE ORDER</button>
      </div>
    </form>
  </div>
  </div>
  </div>
  
    </div>
  </div>
  

  
  

</div>
  <script src="{% static 'js/create_order.js' %}"></script>
  {% endblock%}

orderio/templates/employee/employee_profile.html
{% extends "../user-base.html" %}
{% load static %}
{% block title %}
Profile
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/public_profile.css' %}">
<div class="container rounded bg-white mt-5 mb-5 shadow">
    <div class="row">
        <div class="col-md-4 border-right">
            <form action="" enctype="multipart/form-data" method="post">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" width="150px" src="{{request.user.employee.profile_pic.url}}">
                {{e_form.profile_pic}}
                <span> 
                </span></div>
        </div>
        <div class="col-md-8 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">User Profile</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">Name</label><br>
                        <span class="form-control border-0 fw-bold fs-4">{{fl_form.first_name}}</span>
                    </div>
                    <div class="col-md-6"><label class="labels">Surname</label>
                        <br><span class="form-control border-0 fw-bold fs-4">{{fl_form.last_name}}</span>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        <label class="labels">Email</label>
                        <span class="form-control border-0 fw-bold fs-4">{{fl_form.email}}</span>
                    </div>
                    <div class="col-md-12">
                        <label class="labels">Mobile Number</label>
                        <span class="form-control border-0 fw-bold fs-4">{{e_form.phone_number}}</span>
                    </div>
                    <div class="col-md-12">
                        <label class="labels">Department</label>
                        <span class="form-control border-0 fw-bold fs-4">
                            {{e_form.department}}
                        </span>
                    </div>
                    <div class="col-md-12">
                        <label class="labels">Account created at</label>
                        <span class="form-control border-0 fw-bold fs-4">
                            {{request.user.employee.created_at}}
                        </span>
                    </div>
                    {% if form.errors %}
                                  {% for field in form %}
                                      {% for error in field.errors %} 
                                          <div class="alert alert-danger">
                                              <strong>{{ error|escape }}</strong>
                                          </div>
                                      {% endfor %}
                                  {% endfor %}
                                {% endif %}
                    <div class="col-md-12 text-center">
                        {% csrf_token %}
                        <input type="submit" value="Update Profile" class="btn btn-primary">
                    </div>
                </div>
            </form>
            </div>
        </div>
        
    </div>
</div>



{% endblock content %}

orderio/templates/employee/error-template.html
{% extends "../user-base.html" %}
{% load static %}
{% block title %}
  Error
{% endblock title %}
{% block content %}
  <!-- Begin Page Content -->
  <div class="container-fluid d-flex justify-content-center align-items-center" style="height:80vh;">

    <!-- 404 Error Text -->
    <div class="text-center">
        <div class="error mx-auto" data-text="OOPS">OOPS</div>
        
        <p class="text-info fs-2 fw-bold mb-0">{{text}}</p>
        <a href="{% url 'employee:index' %}">&larr; Back to Dashboard</a>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}
                

            

orderio/templates/employee/index.html
{% extends "../user-base.html" %}
{% load static %}
{% block title %}
  Home
{% endblock title %}
{% block content %}
{% for message in messages %}
<div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<div class="row">
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Your daily allowance</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{request.user.employee.daily_allowance}}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Budget available</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{budget_available}}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-4 col-lg-4 col-md-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Today's menu</h6>
                
            </div>
            <!-- Card Body -->
            <div class="card-body">
              {% if menu %}
              <b class="fs-5 text-dark">{{menu.get_day_name}}</b><br>
              Meals:
              {% for meal in menu.meals.all %}
              <li><a href="{{meal.get_absolute_url}}">{{meal.name}}</a></li>
              {% endfor %}
              
              Menu status:<br> 
              <b class="fs-5 text-dark">
              {% if menu.approved %}
              {% if menu.allowes_orders %}
              <span class="text-success">Available</span>
              <hr>
                <a class="btn btn-primary {% if has_ordered %}disabled{% endif %}" href="{% url 'employee:daily_menu' %}">Order Now</a>
              {% else %}
              <span class="text-danger">Expired</span>
              {% endif %}
                
                
                {% else %}
                <span class="text-warning">Pending</span>
              {% endif %}
              </b><br>
              
              
                {% else %}
                The menu for {{day_name}} is not ready yet!
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-xl-8 col-lg-8 col-md-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Recent Orders</h6>
                
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="table-responsive">
                <table class="table table-striped">
                    <thead class="bg-primary text-white fw-bold">
                        <tr>
                            <th>Created at</th>
                            <th>Meals</th>
                            <th>Status</th>
                            <th>Cost</th>
                            <th>Action</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <td> {{order.created_at}}</td>
                            <td>{% for meal in order.meals.all %}
                                {{meal}}
                              {% endfor %}</td>
                              <td class='text-{% if order.order_status == "Accepted" %}success{% elif order.order_status == "Pending" %}warning{% else %}danger{% endif %}'>
                                {{order.order_status}}
                            </td>
                            <td>${{order.order_cost}} </td>
                            <td>
                            {% if order.order_status == 'Pending' %}
                            <a href="{% url 'order:delete_order' order.pk %}" class="btn btn-danger btn-sm">Delete</a>
                               {% endif %}</td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
                <div class="text-center"><a href="{% url 'order:user_order_history' %}">View all your previous orders</a></div>
            </div>
        </div>
    </div>
  </div>

{% endblock content %}

orderio/templates/employee/order_history.html
{% extends "../user-base.html" %}
{% block title %}
  Order History
{% endblock title %}
{% block content %}
<div class="container-fluid">
  <h1 class="h3 mb-2 text-gray-800">Your Order History</h1>
  <p class="mb-4">Here you can see all your previous orders.</p>
 
  <div class="card shadow mb-4">
      <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">
            {% if request.user.first_name and request.user.last_name%}
            {{request.user.first_name}} {{request.user.last_name}}{%else%}
            {{request.user.username}}{% endif %}'s Orders</h6>
      </div>
      <div class="card-body">
          <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="bg-primary text-white fw-bold">
                  <tr>
                      <th>Created at</th>
                      <th>Meals</th>
                      <th>Status</th>
                      <th>Cost</th>
                  </tr>
                </thead>          
                  <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{order.created_at}}</td>
                        <td>{% for meal in order.meals.all %}
                            {{meal}}
                          {% endfor %}</td>
                        <td class='text-{% if order.order_status == "Accepted" %}success{% elif order.order_status == "Pending" %}warning{% else %}danger{% endif %}'>
                          {{order.order_status}}


                        </td>
                        <td>${{order.order_cost}}</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
              </table>
          </div>
      </div>
  </div>
 
 </div>
{% endblock content %}

orderio/templates/employee/public_profile.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
  {{employee.user.username}}
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/public_profile.css' %}">
<div class="container rounded bg-white mt-5 mb-5 shadow">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" width="150px" src="{{employee.profile_pic.url}}">
                <span class="font-weight-bold">{{employee.user.username}}</span>
                <span class="text-black-50"> {{employee.user.email}}</span>
                <span> 
                </span></div>
        </div>
        <div class="col-md-8 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">User Profile</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">Name</label><br>
                        <span class="form-control border-0 fw-bold fs-4">{{employee.user.first_name}}</span>
                    </div>
                    <div class="col-md-6"><label class="labels">Surname</label>
                        <br><span class="form-control border-0 fw-bold fs-4">{{employee.user.last_name}}</span>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        <label class="labels">Mobile Number</label>
                        <span class="form-control border-0 fw-bold fs-4">{{employee.phone_number}}</span>
                    </div>
                    <div class="col-md-12">
                        <label class="labels">Department</label>
                        <span class="form-control border-0 fw-bold fs-4">
                            {{employee.department}}
                        </span>
                    </div>
                    <div class="col-md-12">
                        <label class="labels">Account created at</label>
                        <span class="form-control border-0 fw-bold fs-4">
                            {{employee.created_at}}
                        </span>
                    </div>
                    <div class="col-md-12">
                        <label class="labels">Total orders</label>
                        <span class="form-control border-0 fw-bold fs-4">
                            {{employee.order_set.all.count}}
                        </span>
                    </div>
                </div>
                
            </div>
        </div>
        
    </div>
</div>
</div>
</div>
{% endblock content %}

orderio/templates/employee/view_weekly_menu.html
{% extends "../user-base.html" %}
{% block title %}
  Weekly Menu
{% endblock title %}
{% block content %}
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Menus for this week</h1>
    <p class="mb-4">Here you can see all the menus scheduled for this week.<br>
        <span class="text-info">Click on the meal to view more details.</span>
   </p>
   
  <div class="row">
  {% for menu in wm.menu_set.all %}
  
    <div class="col-lg-4 col-md-6">
  <div class="card shadow mb-4 ">
    <!-- Card Header - Accordion -->
    <a href="#collapseCardExample{{menu.id}}" class="d-block card-header py-3" data-toggle="collapse"
        role="button" aria-expanded="true" aria-controls="collapseCardExample{{menu.id}}">
        <h6 class="m-0 font-weight-bold text-primary">{{menu.get_day_name}}</h6>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse show" id="collapseCardExample{{menu.id}}">
        <div class="card-body">
          Meals:
          {% for meal in menu.meals.all %}
          <li><a href="{{meal.get_absolute_url}}">{{meal.name}}</a></li>
          {% endfor %}
          <hr>
          <div>Status: {% if menu.approved %}
            <span class="text-success fw-bold">Approved</span>
              {% else %}
              <span class="text-info fw-bold">Pending</span>
            {% endif %} </div>
          
        </div>
    </div>
  </div>
  </div>
  
  
  {% endfor %}
  </div>
  </div>



  

{% endblock content %}