orderio/chat/urls.py
from django.urls import path
from chat import views
app_name = "chat"
urlpatterns = [
    path("",views.index,name="index"),
    path("draft",views.draft,name="draft"),
    path("read_message/<int:pk>",views.read_message,name="read_message"),
    path("create_thread/<int:pk>",views.create_thread,name="create_thread")
]

orderio/manager/urls.py
from django.urls import path
from . import views
app_name = "manager"
urlpatterns = [
    
    path("",views.index, name="index"),
    #reports
    path("reports",views.reports_index,name="reports_index"),
    path("user_spendings",views.user_spendings,name="user_spendings"),
    path("total_orders_by_department",views.total_orders_by_department,name="total_orders_by_department"),
    path("most_ordered_meals",views.most_ordered_meals,name="most_ordered_meals"),
    path("most_ordered_category",views.most_ordered_category,name="most_ordered_category"),
    
    #chart links
    path("chart_user_spendings/<int:pk>",views.chart_user_spendings,name='chart_user_spendings'),
    path("chart_total_orders_by_department/<int:pk>",views.chart_total_orders_by_department,name="chart_total_orders_by_department"),
    path("number_of_orders_by_day",views.number_of_orders_by_day,name="number_of_orders_by_day"),
    path("chart_most_ordered_meals/<int:pk>",views.chart_most_ordered_meals,name="chart_most_ordered_meals"),
    path("chart_most_ordered_category",views.chart_most_ordered_category,name="chart_most_ordered_category"),
]

orderio/menu/urls.py
from django.urls import path
from . import views

app_name = "menu"
urlpatterns = [
    path("create_menu/<int:weekly_id>/",views.create_menu,name="create_menu"),
    path("add_to_menu/<int:meal_pk>/<int:menu_pk>",views.add_to_menu,name="add_to_menu"),
    path("remove_from_menu/<int:meal_pk>/<int:menu_pk>",views.remove_from_menu,name="remove_from_menu"),
    path("update_menu/<int:pk>",views.update_menu,name="update_menu"),
    path("approve_menu/<int:pk>",views.approve_menu,name="approve_menu"),
    path("<int:pk>/",views.view_menu,name="view_menu"),
    path("update_session/",views.update_session,name="update_session"),
    path("delete_menu/<int:pk>",views.delete_menu,name="delete_menu"),
    #weekly
    path("weekly_menu",views.weekly_menu,name="weekly_menu"),
    path("view_weekly_menu/<int:week>/<int:year>",views.view_weekly_menu,name="view_weekly_menu"),
    path("all_weekly_menus/",views.all_weekly_menus,name="all_weekly_menus"),
    # path("create_weekly_menu",views.create_weekly_menu,name="create_weekly_menu"),
    # path("update_weekly_menu",views.update_weekly_menu,name="update_weekly_menu"),
    # path("delete_weekly_menu",views.delete_weekly_menu,name="delete_weekly_menu"),
    
]

orderio/order/urls.py
from django.urls import path
from . import views
app_name = "order"
urlpatterns = [
    path("daily_orders",views.daily_orders,name="daily_orders"),
    path("create_order",views.create_order,name="create_order"),
    path("<int:pk>",views.view_order,name="view_order"),
    path("user_order_history",views.user_order_history,name="user_order_history"),
    path("delete_order/<int:pk>",views.delete_order,name="delete_order"),
    path("change_order_status/<int:pk>/<int:status>",views.change_order_status,name="change_order_status"),
    path("add_to_order",views.add_to_order,name="add_to_order"),
    path("all_orders_this_week",views.all_orders_this_week,name="all_orders_this_week"),
    path("full_order_history",views.full_order_history,name="full_order_history"),
    path("custom_order/",views.custom_order,name="custom_order")
]

orderio/orderio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from main.views import handle_not_found
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace="main")),
    path('manager/', include('manager.urls',namespace="manager")),
    path('employee/', include('employee.urls',namespace="employee")),
    path('account/', include('account.urls')),
    path('order/', include('order.urls',namespace="order")),
    path('menu/', include('menu.urls',namespace="menu")),
    path('meal/', include('meal.urls',namespace="meal")),
    path('notification/', include('notification.urls',namespace="notification")),
    path('chat/', include('chat.urls',namespace="chat")),
]
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'main.views.handle_not_found'

orderio/manager/models.py
from django.db import models

# Create your models here.

orderio/manager/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from main.decorators import allowed_users
from employee.models import Department
from account.models import CustomUser
from menu.models import WeeklyMenu,Menu
from order.models import Order
from django.http import JsonResponse
from django.utils import timezone
from datetime import date
from meal.models import Meal,Category
import random
from django.db.models import Q

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def index(request):
    week = timezone.now().isocalendar().week
    day = timezone.now().isoweekday()
    year = timezone.now().isocalendar().year
    total_users = CustomUser.objects.filter(role__name="user").count()
    try:
        weekly_menu = get_object_or_404(WeeklyMenu,week=week,year=year)
        menu = weekly_menu.menu_set.get(created_for=day)
        
    except:
        menu = ""
    this_week_orders = Order.objects.filter(created_at__week=week).count()
    context= {
              "this_week_orders":this_week_orders,
              "menu":menu,
              "total_users":total_users,
              }
    return render(request,'manager/index.html',context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def reports_index (request):
    return render(request,'manager/reports_index.html')

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def user_spendings(request):
    users = CustomUser.objects.filter(role__name = "user")
    context ={"users":users}
    return render(request,"manager/user_spendings.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def chart_user_spendings(request,pk):
    user = get_object_or_404(CustomUser,pk=pk)
    weekly_menus = WeeklyMenu.objects.all()
    total_spent = 0
    labels = []
    data = []
    
    for weekly_menu in weekly_menus.order_by('created_at')[:30]:
        for order in user.employee.order_set.filter(menu__weekly_menu = weekly_menu):
            total_spent+=order.order_cost
        labels.append(str(weekly_menu))
        data.append(total_spent)
        total_spent=0
    
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def total_orders_by_department(request):
    weekly_menus = WeeklyMenu.objects.all()
    context = {"weekly_menus":weekly_menus}
    return render(request,"manager/total_orders_by_department.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def chart_total_orders_by_department(request,pk):
    weekly_menu = get_object_or_404(WeeklyMenu,pk=pk)
    labels = []
    data = []
    order_count = 0
    departments = Department.objects.all()
    for department in departments:
        for employee in department.employee_set.all():
            order_count+=employee.order_set.filter(menu__weekly_menu = weekly_menu).count()
        labels.append(department.name)
        data.append(order_count)
        order_count = 0
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })
    
@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def most_ordered_meals(request):
    weekly_menus = WeeklyMenu.objects.all()
    context = {"weekly_menus":weekly_menus}
    return render(request,"manager/most_ordered_meals.html",context)

def chart_most_ordered_meals(request,pk):
    labels = []
    data = []
    if pk !=0:
        weekly_menu = get_object_or_404(WeeklyMenu,pk=pk)
    meals=Meal.objects.all()
    for meal in meals:
        labels.append(str(meal))
        if pk ==0:
            data.append(meal.order_set.all().count())
        else:
            data.append(meal.order_set.filter(menu__weekly_menu=weekly_menu).count())
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])   
def number_of_orders_by_day(request):
    labels = []
    data = []
    upper_bound = Menu.objects.filter(approved=True).count()
    lower_bound = upper_bound-50 if upper_bound>50 else 0

    menus = Menu.objects.filter(approved=True).order_by('-weekly_menu','created_for',)[lower_bound:upper_bound]
    for menu in menus:
        labels.append(str(date.fromisocalendar(menu.weekly_menu.year,menu.weekly_menu.week,menu.created_for,).strftime("%a, %d/%b/%y")))
        data.append(menu.order_set.filter(Q(order_status="Accepted")|Q(order_status="Pending")).count())
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def most_ordered_category(request):
    
    return render(request,"manager/most_ordered_category.html")
 
def chart_most_ordered_category(request):
    labels = []
    data = []
    bgColor = []
    total_orders = 0
    categories = Category.objects.all()
    #qe te mos ndryshojne
    random.seed(1)
    for category in categories:
        labels.append(category.name)
        bgColor.append(f'rgba({random.randint(0,255)}, {random.randint(0,255)}, {random.randint(0,255)},{random.random()})')
        if category.meal_set.all().count()>0:
            for meal in category.meal_set.all():      
                total_orders+=meal.order_set.all().count()
            data.append(total_orders)
            
            total_orders=0
        else:
            data.append(0)
    return JsonResponse(data={
        'labels': labels,
        'data': data,
        'bgColor':bgColor
    })

orderio/templates/manager/error-template.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
  Error
{% endblock title %}
{% block content %}
  <!-- Begin Page Content -->
  <div class="container-fluid d-flex justify-content-center align-items-center" style="height:80vh;">

    <!-- 404 Error Text -->
    <div class="text-center">
        <div class="error mx-auto" data-text="OOPS">OOPS</div>
        
        <p class="text-info fs-2 fw-bold mb-0">{{text}}</p>
        <a href="{% url 'main:index' %}">&larr; Back to Dashboard</a>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}
                

            

orderio/templates/manager/index.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
Dashboard
{% endblock title %}
{% block content %}
{% for message in messages %}
        <div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
            {{message}}
            <small><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></small>
        </div>
{% endfor %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div>
<div class="row">
  
  

  <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          Total orders this week</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{this_week_orders}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                  </div>
              </div>
          </div>
      </div>
  </div>

 
  <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                          Total users registered</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_users}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-user-tie fa-2x text-gray-300"></i>
                      
                  </div>
              </div>
          </div>
      </div>
  </div>


  <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                          Pending Orders Today</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{pending_orders}}</div>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<div class="row">

  <!-- Area Chart -->
  <div class="col-xl-8 col-lg-8">
      <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div
              class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">Orders Overview</h6>
              
          </div>
          <!-- Card Body -->
          <div class="card-body">
            <div id="container" class="chart-area" style="width: 100%; height:auto;" data-url="{% url 'manager:number_of_orders_by_day' %}">
              <canvas id="population-chart" ></canvas>
            </div>
          </div>
      </div>
  </div>

  <!-- Pie Chart -->
  <div class="col-xl-4 col-lg-4">
      <div class="card shadow mb-4">
          <!-- Card Header - Dropdown -->
          <div
              class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">Today's menu</h6>
              
          </div>
          <!-- Card Body -->
          <div class="card-body">
            {% if menu %}
            Menu for: <br>
            <b class="fs-5 text-dark">{{menu.get_day_name}}</b><br>
            Meals:
            {% for meal in menu.meals.all %}
            <li><a href="{{meal.get_absolute_url}}">{{meal.name}}</a></li>
            {% endfor %}
            Menu status:<br> 
            <b class="fs-5 text-dark">
            {% if menu.approved %}
              Approved
              {% else %}
              Pending
            {% endif %}
            </b><br>
            <hr>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                {% if not menu.approved %}
                <button data-url="{% url 'menu:approve_menu' menu.pk %}" value="{% url 'menu:approve_menu' menu.pk %}" class="btn btn-success btn-sm" id="approve-btn{{menu.pk}}"  data-bs-toggle="modal" data-bs-target="#approveModal"> 
                      <i class="fas fa-check"></i><span class="text">Approve</span></button>
                {% else %}
                <a href="{{menu.get_absolute_url}}" class="btn btn-info btn-sm"><i class="far fa-eye "></i> View menu</a>
                {% endif %}
                
              
            <a href="{% url 'menu:weekly_menu' %}" class="btn btn-primary btn-sm ml-1">
              <i class="fas fa-calendar-week"></i> Menus for this week
            </a>
            </div>
            
              {% else %}
              You have not created a menu for today!
              <hr>
              <a href="{% url 'menu:weekly_menu' %}" class="btn btn-info">
                 Create
              </a>
              {% endif %}
          </div>
      </div>
      <div class="card shadow mb-4">
        <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Custom Order</h6>
        
    </div>
    <div class="card-body">
       <div class="text-dark mb-3"> By clicking the button below you can create a custom order, no matter if the menu is accepted, expired or not.</div>
        <div class="text-center">
        <a href="{% url 'order:custom_order' %}"  class="btn btn-warning">Create custom order</a>
    </div></div>
      </div>
      
      
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="approveModal" tabindex="-1" aria-labelledby="approveModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="approveModalLabel">You are about to approve a menu!</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to <span class="text-warning">approve</span> this menu?<br>
          <hr>
          <b class="text-danger">Be careful!</b><br> 
          Once you approve the menu, <b><i>you cannot edit or delete it anymore</i></b>!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-warning" id="conf-btn">Approve</button>
        </div>
      </div>
    </div>
  </div>
  
<script src="{% static 'js/danger-confirmation.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src='{% static "js/manager-dashboard.js" %}'></script> 

{% endblock%}

orderio/templates/manager/most_ordered_category.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
Most Ordered Meal Category
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" integrity="sha512-yVvxUQV0QESBt1SyZbNJMAwyKvFTLMyXSyBHDO4BG5t7k/Lw34tyqlSDlKIrIENIzCl+RVUNjmCPG+V/GMesRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="container-fluid">
    
  <h1 class="h3 mb-2 text-gray-800">Most Ordered Meal Category</h1>

<div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Pie Chart</h6>
  </div>
  <div class="card-body ">
      <div class="row">
        <div class="col-lg-2">
          <p class="mb-4">Hover to see the total, of how many times the meals from the category have been in an order.</p>
        </div>
        <div class="col-lg-10">
          <div id="container" class="chart-area" style="width: 100%; height:auto;" data-url="{% url 'manager:chart_most_ordered_category' %}">
            <canvas id="population-chart" ></canvas>
          </div>
        </div>
        
      </div>
      
      
      </div>
  </div>
</div>






<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" integrity="sha512-rMGGF4wg1R73ehtnxXBt5mbUfN9JUJwbk21KMlnLZDJh7BkPmeovBuddZCENJddHYYMkCh9hPFnPmS9sspki8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src='{% static "js/most_ordered_category.js" %}'></script> 
{% endblock content %}

orderio/templates/manager/most_ordered_meals.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
most Ordered Meals
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" integrity="sha512-yVvxUQV0QESBt1SyZbNJMAwyKvFTLMyXSyBHDO4BG5t7k/Lw34tyqlSDlKIrIENIzCl+RVUNjmCPG+V/GMesRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="container-fluid">
    
  <h1 class="h3 mb-2 text-gray-800">most Ordered Meals</h1>
<p class="mb-4">Select option to see how many orders contain each meal.</p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Chart</h6>
  </div>
  <div class="card-body ">
      <div class="row">
        <div class="col-lg-3">
          <h5>Select or search for the period.</h5>
          <select id="user-select" class="chosen">
            <option default>Select week</option>
            <option value="0" data-url="{% url 'manager:chart_most_ordered_meals' 0 %}">All time</option>
              {% for weekly_menu in weekly_menus%}
                <option value="{{weekly_menu.id}}" data-url="{% url 'manager:chart_most_ordered_meals' weekly_menu.id %}">
                  {{weekly_menu}}
                </option>
              {% endfor %}
          </select>
        </div>
        <div class="col-lg-9">
          <div id="container" style="width: 100%; height:auto;">
            <canvas id="population-chart" ></canvas>
          </div>
        </div>
        
      </div>
      
      
      </div>
  </div>
</div>






<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" integrity="sha512-rMGGF4wg1R73ehtnxXBt5mbUfN9JUJwbk21KMlnLZDJh7BkPmeovBuddZCENJddHYYMkCh9hPFnPmS9sspki8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> 
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src='{% static "js/most_ordered_meals.js" %}'></script> 
<script type="text/javascript">
  $(".chosen").chosen();
</script>
{% endblock content %}

orderio/templates/manager/reports_index.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
  Reports
{% endblock title %}
{% block content %}
<style>
    .card a:hover
    { text-decoration: none;
    }
    .card a div:hover{
        color: black !important;
    }
    .row .card {
        border: 1px solid #4e73df;
        text-align: center;
    }
</style>
<div class="container-fluid">
    
    <h1 class="h3 mb-2 text-gray-800">Reports</h1>
 <p class="mb-4">This is the index page report. Click on the type of the report you wish to view below.</p>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">All reports</h6>
    </div>
    <div class="card-body ">
        <div class="row">
            <div class="col-lg-4">
                <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 100%;" src="{% static 'img/reports.svg' %}" alt="...">
            </div>
            <div class="col-lg-8">
                <div class="row  justify-content-evenly">
                    <div class="card mb-4 border-bottom-primary col-lg-5">
                        <a href="{% url 'manager:total_orders_by_department' %}">
                        <div class="card-body fw-bold text-primary fs-5">
                            Total Orders by Department
                        </div>
                    </a>
                    </div>
                    <div class="card mb-4 border-bottom-primary col-lg-5">
                        <a href="{% url 'manager:user_spendings' %}"><div class="card-body fw-bold text-primary fs-5">
                            User Spendings
                        </div></a>
                    </div>
                    <div class="card mb-4 border-bottom-primary col-lg-5">
                        <a href="{% url 'manager:most_ordered_meals' %}"><div class="card-body fw-bold text-primary fs-5">
                            Most ordered meals
                        </div></a>
                    </div>
                    <div class="card mb-4 border-bottom-primary col-lg-5">
                        <a href="{% url 'manager:most_ordered_category' %}"><div class="card-body fw-bold text-primary fs-5">
                            Most ordered Category
                        </div></a>
                    </div>
                    <div class="card mb-4 border-bottom-primary col-lg-5">
                        <a href="{% url 'menu:all_weekly_menus' %}"><div class="card-body fw-bold text-primary fs-5">
                            Weekly menu History
                        </div></a>
                    </div>
                </div>
                
  
            </div>
        </div>
        
        
        </div>
    </div>
</div>


{% endblock content %}

orderio/templates/manager/total_orders_by_department.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
Total Orders by Department
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" integrity="sha512-yVvxUQV0QESBt1SyZbNJMAwyKvFTLMyXSyBHDO4BG5t7k/Lw34tyqlSDlKIrIENIzCl+RVUNjmCPG+V/GMesRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="container-fluid">
    
  <h1 class="h3 mb-2 text-gray-800">Total Orders by Department</h1>
<p class="mb-4">Select week to see how much orders has each department placed.</p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Chart</h6>
  </div>
  <div class="card-body ">
      <div class="row">
        <div class="col-lg-3">
          <h5>Select or search for the period.</h5>
          <select id="user-select" class="chosen">
            <option default>Select week</option>
              {% for weekly_menu in weekly_menus%}
                <option value="{{weekly_menu.id}}" data-url="{% url 'manager:chart_total_orders_by_department' weekly_menu.id %}">
                  {{weekly_menu}}
                </option>
              {% endfor %}
          </select>
        </div>
        <div class="col-lg-9">
          <div id="container" style="width: 100%; height:auto;">
            <canvas id="population-chart" ></canvas>
          </div>
        </div>
        
      </div>
      
      
      </div>
  </div>
</div>






  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" integrity="sha512-rMGGF4wg1R73ehtnxXBt5mbUfN9JUJwbk21KMlnLZDJh7BkPmeovBuddZCENJddHYYMkCh9hPFnPmS9sspki8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script src='{% static "js/total_orders_by_department.js" %}'></script> 
  <script type="text/javascript">
    $(".chosen").chosen();
  </script>
{% endblock content %}

orderio/templates/manager/user_spendings.html
{% extends "../manager-base.html" %}
{% load static %}


{% block title %}
User Spendings Each Week
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" integrity="sha512-yVvxUQV0QESBt1SyZbNJMAwyKvFTLMyXSyBHDO4BG5t7k/Lw34tyqlSDlKIrIENIzCl+RVUNjmCPG+V/GMesRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="container-fluid">
    
  <h1 class="h3 mb-2 text-gray-800">User Spendings Each Week</h1>
<p class="mb-4">Select a user to see how they have spent each week.</p>
<div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Chart</h6>
  </div>
  <div class="card-body ">
      <div class="row">
        <div class="col-lg-3">
          <h5>Select or search for the user.</h5>
          <select id="user-select" class="chosen">
            <option default>Select user</option>
              {% for user in users %}
                <option value="{{user.id}}" data-url="{% url 'manager:chart_user_spendings' user.id %}">
                  {{user}} | {{user.first_name}} {{user.last_name}}
                </option>
              {% endfor %}
          </select>
        </div>
        <div class="col-lg-9">
          <div id="container" style="width: 100%; height:auto;">
            <canvas id="population-chart" data-url="{% url 'manager:chart_user_spendings' 2 %}"></canvas>
          </div>
        </div>
        
      </div>
      
      
      </div>
  </div>
</div>






  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" integrity="sha512-rMGGF4wg1R73ehtnxXBt5mbUfN9JUJwbk21KMlnLZDJh7BkPmeovBuddZCENJddHYYMkCh9hPFnPmS9sspki8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script src='{% static "js/user_spendings.js" %}'></script> 
  <script type="text/javascript">
    $(".chosen").chosen();
  </script>
{% endblock content %}