orderio/chat/urls.py
from django.urls import path
from chat import views
app_name = "chat"
urlpatterns = [
    path("",views.index,name="index"),
    path("draft",views.draft,name="draft"),
    path("read_message/<int:pk>",views.read_message,name="read_message"),
    path("create_thread/<int:pk>",views.create_thread,name="create_thread")
]

orderio/menu/urls.py
from django.urls import path
from . import views

app_name = "menu"
urlpatterns = [
    path("create_menu/<int:weekly_id>/",views.create_menu,name="create_menu"),
    path("add_to_menu/<int:meal_pk>/<int:menu_pk>",views.add_to_menu,name="add_to_menu"),
    path("remove_from_menu/<int:meal_pk>/<int:menu_pk>",views.remove_from_menu,name="remove_from_menu"),
    path("update_menu/<int:pk>",views.update_menu,name="update_menu"),
    path("approve_menu/<int:pk>",views.approve_menu,name="approve_menu"),
    path("<int:pk>/",views.view_menu,name="view_menu"),
    path("update_session/",views.update_session,name="update_session"),
    path("delete_menu/<int:pk>",views.delete_menu,name="delete_menu"),
    #weekly
    path("weekly_menu",views.weekly_menu,name="weekly_menu"),
    path("view_weekly_menu/<int:week>/<int:year>",views.view_weekly_menu,name="view_weekly_menu"),
    path("all_weekly_menus/",views.all_weekly_menus,name="all_weekly_menus"),
    # path("create_weekly_menu",views.create_weekly_menu,name="create_weekly_menu"),
    # path("update_weekly_menu",views.update_weekly_menu,name="update_weekly_menu"),
    # path("delete_weekly_menu",views.delete_weekly_menu,name="delete_weekly_menu"),
    
]

orderio/orderio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from main.views import handle_not_found
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace="main")),
    path('manager/', include('manager.urls',namespace="manager")),
    path('employee/', include('employee.urls',namespace="employee")),
    path('account/', include('account.urls')),
    path('order/', include('order.urls',namespace="order")),
    path('menu/', include('menu.urls',namespace="menu")),
    path('meal/', include('meal.urls',namespace="meal")),
    path('notification/', include('notification.urls',namespace="notification")),
    path('chat/', include('chat.urls',namespace="chat")),
]
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'main.views.handle_not_found'

orderio/menu/models.py
from django.db import models
from meal.models import Meal
from django.utils import timezone
from django.urls import reverse
from datetime import date

# Create your models here.
class WeeklyMenu(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    week = models.IntegerField(default=int(timezone.now().isocalendar().week))
    year = models.IntegerField(default=int(timezone.now().isocalendar().year))
    
    def __str__(self):
        return f"{date.fromisocalendar(self.year,self.week,1).strftime('%d/%b/%y')}-{date.fromisocalendar(self.year,self.week,7).strftime('%d/%b/%y')}"
    
    class Meta:
        ordering = ('-year','-week',)
    
    def get_absolute_url(self):
        return reverse("menu:view_weekly_menu", kwargs={"week": self.week,"year":self.year})
    
    def get_total_order_count(self):
        total = 0
        for menu in self.menu_set.all():
            total += menu.order_set.all().count()
        return total
    

class Menu(models.Model):
    CAPACITY = 7
    
    Monday = 1
    Tuesday =2
    Wendnesday = 3
    Thursday = 4
    Friday = 5
    Saturday = 6
    Sunday = 7
    
    DAYS = (
            (Monday,"Monday"),
            (Tuesday,"Tuesday"),
            (Wendnesday,"Wendnesday"),
            (Thursday,"Thursday"),
            (Friday,"Friday"),   
            (Saturday,"Saturday"), 
            (Sunday,"Sunday"),    
            )
    #relationships
    meals = models.ManyToManyField(Meal)
    weekly_menu = models.ForeignKey(WeeklyMenu,null=True,on_delete=models.CASCADE)
    #attributes
    created_at = models.DateTimeField(auto_now_add=True)
    avability = models.IntegerField(default=2)
    approved = models.BooleanField(default=False)
    approved_at = models.DateTimeField(blank=True,null=True)
    created_for = models.IntegerField(choices=DAYS,default=Monday,null=True,blank=True)
    
    
    class Meta:
        ordering = ('weekly_menu','created_for',)
    
    def __str__(self):
        
        try: 
            week = self.weekly_menu.week
            year = self.weekly_menu.year
        except:
            week = ""
            year = ""
        return str(date.fromisocalendar(year,week,self.created_for).strftime("%A, %d/%b/%y"))
    
    def allowes_orders(self):
        return (timezone.now()-self.approved_at)<timezone.timedelta(hours=self.avability)
    
    def get_order_total(self):
        return self.order_set.count()
    
    def get_menu_total_price(self):
        total = 0
        for meal in self.meals.all():
            total+=meal.price
        return total
    
    def get_day_name(self):
        name =""
        for day in Menu.DAYS:
            if day[0] == self.created_for:
                name = day[1]
                break
        return name
 

    def get_absolute_url(self):
        return reverse("menu:view_menu", kwargs={"pk": self.pk})

orderio/order/models.py
from django.db import models
from employee.models import Employee
from meal.models import Meal
from menu.models import Menu
from django.urls import reverse
# Create your models here.

class Order(models.Model):
    STATUS = (
        ("Pending","Pending"),
        ("Accepted","Accepted"),
        ("Denied","Denied")
        )
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE,null=True,blank=True)
    meals = models.ManyToManyField(Meal,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    menu = models.ForeignKey(Menu,blank=True,on_delete=models.CASCADE,null=True,)
    order_status = models.CharField(default="Pending",choices=STATUS,blank=True,null=True,max_length=10)
    order_cost = models.DecimalField(max_digits=6,decimal_places=2,default=0)
    
    class Meta:
        ordering = ("-created_at",)
        
    def get_created_at_date(self):
        return self.created_at.date()
    
    def __str__(self):
        return f"{str(self.created_at.date())} {self.employee.user.username}"
    
    def get_absolute_url(self):
        return reverse("order:view_order", kwargs={"pk": self.pk})
    
    

orderio/menu/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render,reverse
from main.session_handle import Custom_Session
from main.decorators import allowed_users
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from menu.models import WeeklyMenu,Menu
from meal.models import Meal
from menu.custom_functions import user_or_manager
#weekly menu
@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def weekly_menu(request):
    week = timezone.now().isocalendar().week
    year = timezone.now().isocalendar().year

    try:
        weekly_menu = WeeklyMenu.objects.get(week=week,year=year)
    except:
        weekly_menu = WeeklyMenu(week=week,year=year)
        weekly_menu.save()
    menus = weekly_menu.menu_set.all()
    context={"weekly_menu":weekly_menu,"menus":menus}
    return render(request,'menu/weekly_menu.html',context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def all_weekly_menus(request):
    all_weekly_menus = WeeklyMenu.objects.all()
    context={"all_weekly_menus":all_weekly_menus}
    return render(request,"menu/all_weekly_menus.html",context)

@login_required(login_url="login")
def view_weekly_menu(request,week,year):
    try:
        wm = WeeklyMenu.objects.get(week=week,year=year)
    except:
        wm = ""
    context = {"wm":wm}
    return user_or_manager(request,"view_weekly_menu",context)
    
@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def delete_menu(request,pk):
    menu = get_object_or_404(Menu,pk=pk)
    name = menu.get_day_name()
    menu.delete()
    messages.success(request,f"Menu for {name} was deleted successfully!")
    return redirect("menu:weekly_menu")
    
#daily menu
@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def update_menu(request,pk):
    meals = Meal.objects.all()
    menu = get_object_or_404(Menu,pk=pk)
    menu_meals = menu.meals.all()
    item_count = menu.meals.all().count()
    item_price_total = menu.get_menu_total_price()
    if request.method == 'POST':
        
        avability = request.POST.get("avability")
        menu.avability = avability
        menu.save()
        messages.success(request,"Menu has been saved!")
        return redirect("menu:weekly_menu")
    context = {"menu":menu,"menu_meals":menu_meals,"meals":meals,"item_count":item_count,"item_price_total":item_price_total,}
    return render(request,"menu/update_menu.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def approve_menu(request,pk):
    menu = get_object_or_404(Menu,pk=pk)
    menu.approved = True
    menu.approved_at = timezone.now()
    menu.save()
    return redirect(request.META.get('HTTP_REFERER'))

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def view_menu(request,pk):
    menu = get_object_or_404(Menu,pk=pk)
    context = {"menu":menu}
    return render(request,f"menu/view_menu.html",context)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def add_to_menu(request,meal_pk,menu_pk):
    print(meal_pk)
    menu = get_object_or_404(Menu,pk=menu_pk)
    meal = get_object_or_404(Meal,pk=meal_pk)
    item_count = menu.meals.all().count()
    if item_count >= Menu.CAPACITY:
            messages.warning(request,f"You cannot add more than {Menu.CAPACITY} meals")
            return redirect(reverse("menu:update_menu",kwargs={"pk":menu.pk}))
    menu.meals.add(meal)
    return redirect("menu:update_menu",pk=menu_pk)

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def remove_from_menu(request,meal_pk,menu_pk):
    menu = get_object_or_404(Menu,pk=menu_pk)
    meal = get_object_or_404(Meal,pk=meal_pk)
    menu.meals.remove(meal)
    return redirect("menu:update_menu",pk=menu_pk)
       
@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def index(request):
    return render(request,'manager/index.html')

@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def create_menu(request,weekly_id):
    meals = Meal.objects.all()
    weekly_menu = get_object_or_404(WeeklyMenu,id=weekly_id) 
    all_options = Menu.DAYS
    available_options = []
    ss = Custom_Session(request)
    for meal in ss.get_menu_items():
        meals=meals.exclude(pk=meal)
    for day in all_options:
        if not weekly_menu.menu_set.filter(created_for=day[0]):
            available_options.append(int(day[0]))
    if request.method == 'POST':
        
        weekday = request.POST.get('weekday')
        menu_meals_session = ss.get_menu_items()
        if len(menu_meals_session) > Menu.CAPACITY:
            return HttpResponse(f"You cannot add more than {Menu.CAPACITY} meals")
        avability = request.POST.get('menu_avability')  
        
        if weekly_menu.menu_set.filter(created_for=weekday):
            return HttpResponse(f"A menu for {Menu.DAYS[int(weekday)-1][1]} has already been created!")
        else:
            menu = Menu(created_for=weekday,avability=avability,weekly_menu=weekly_menu)
            menu.save()
            menu.meals.set(menu_meals_session)
            menu.save()
            ss.clear()
            messages.success(request,f"Your menu for {Menu.DAYS[int(weekday)-1][1]} has been created!")
            return redirect("menu:weekly_menu")
    context = {
        "meals":meals,
        "available_options" : available_options,
        "all_options" : all_options
    }
    return render(request,"menu/create_menu.html",context)

    
@login_required(login_url="login")
@allowed_users(allowed_roles=['manager'])
def update_session(request):
    ss = Custom_Session(request)
    if request.POST.get('action') == 'add':
        meal_id = int(request.POST.get('meal_id'))
        meal = get_object_or_404(Meal,pk=meal_id)
        ss.add(product=meal)
        response = JsonResponse({"id": meal.id})
        return response
    if request.POST.get('action') == 'remove':
        meal_id = str(request.POST.get('meal_id'))
        ss.remove(product=meal_id)
        response = JsonResponse({"id": meal_id})
        return response
        

orderio/templates/menu/all_weekly_menus.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
Weekly Menu History
{% endblock title %}
{% block content %}

<!-- Custom styles for this page -->

{% for message in messages %}
<div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
 <!-- Page Heading -->
 <div class="container-fluid">
 <h1 class="h3 mb-2 text-gray-800">Weekly Menu History</h1>
 <p class="mb-4">Click on the meal name to view more details.</p>

 <div class="card shadow mb-4">
     <div class="card-header py-3">
         <h6 class="m-0 font-weight-bold text-primary">All Weekly Menus</h6>
     </div>
     <div class="card-body">
         <div class="table-responsive">
             <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                 <thead>
                     <tr>
                       <th>Weekly Menu</th>

                      <th>Created At</th>
                      <th>Action</th>
                     </tr>
                 </thead>             
                 <tbody>
                  {% for wm in all_weekly_menus %}
                   <tr>
                     <td>  <a href="{{wm.get_absolute_url}}">Week: {{wm.week}} Year: {{wm.year}}</a><br></td>
                     <td>{{wm.created_at}}</td>
                     <td>
                      <a href="{{wm.get_absolute_url}}" class="btn btn-sm btn-info">View</a>  
                     
                   </tr>
                   {% endfor %}

                 </tbody>
             </table>
         </div>
     </div>
 </div>

</div>


{% endblock content %}


{% for wm in all_weekly_menus %}
    Week: <a href="{{wm.get_absolute_url}}">{{wm.week}} </a><br>
    Year: {{wm.year}}<br>
    Created at: {{wm.created_at}}<br>
    Total Order Count: {{wm.get_total_order_count}}<br>
    <a href="{{wm.get_absolute_url}}"> More Details </a>
    <br>
{% endfor %}

orderio/templates/menu/create_menu.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
New Menu
{% endblock title %}
{% block content %}

<div class="container-fluid" >
  <h1 class="h3 mb-2 text-gray-800">Create menu</h1>
  <p class="mb-4">Add or remove meals from the menu. Click continue when you are done.</p>
  <!-- meal choosing -->
  <div class="row " >
    <div class="col-lg-7 col-md-7  card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Meal List</h6>
      </div>
      <div class="table-responsive" >
          <table  class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr class="bg-dark text-white">
                <th>Meal</th>
                <th>Calories</th>
                <th>Price</th>
                <th>Description</th>
                <th>Category</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody id="meal-table-body">
              {% for meal in meals %}
                <tr>
                  
                  <td><a href="{{meal.get_absolute_url}}">{{meal.name}}</a></td>
                  <td>{{meal.calories}} </td>
                  <td>{{meal.price}}
                    
                    
                    
                  <td>{{meal.description|truncatechars:50}}</td>
                  <td>{{meal.category.name}}</td>
                  <td>
                    
                    <button class="btn btn-primary " id="add-btn{{meal.id}}" value="{{meal.id}}"
                      data-url="{% url 'menu:update_session' %}" {% if bag|length >= menu_cap %}disabled{% endif %} >Add</button>

                      
                    
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        
      </div>
    </div>
    <div class="col-md-5 col-lg-4 order-md-last">
      <div id="menu-items">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your menu</span>

          <span class="badge bg-primary rounded-pill" id="stuff" 
          data-bl = "{{bag|length}}" data-mc= "{{menu_cap}}"
          >{% with bag|length as b %}
            {{b}}
            {% endwith %}</span>
        </h4>

        <ul class="list-group mb-3">
          {% if bag|length >= menu_cap %}
          <div class="alert alert-danger">Maximum meals allowed are {{menu_cap}}!</div>
          
          {% endif %}
          {% for i in bag.get_menu_items.values %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">{{i.name}}</h6>
              <small class="text-muted">{{i.description|truncatechars:30}}</small>
            </div>
            <span class="text-muted">${{i.price}}
              <button class="btn" id="del-btn{{i.id}}" value="{{i.id}}" data-url="{% url 'menu:update_session' %}">
                <i class="bi bi-x-lg text-danger"></i>
              </button></span>

          </li>
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Menu total price (USD)</span>
            <strong>${{bag.get_total_price|floatformat:2}}</strong>
          </li>
        </ul>
        {% csrf_token %}
        {% if bag|length > 0 %}
        <div class="card p-2 " id="show">
          <button type="submit" class="btn btn-info hw-3 text-white">Continue</button>
        </div>
        <form class="card p-2 invisible" action="" method="post">
          {% csrf_token %}
          <div class="input-group">
            <select name="weekday">
              {% for option in available_options %}
              <option value="{{option}}">
                {% for day in all_options %}
                {% if day.0 == option %}
                {{day.1}}
                {% endif %}
                {% endfor %}
              </option>
              {% endfor %}
            </select>
            <input type="number" required name="menu_avability" class="form-control" placeholder="Avability">
            <button type="submit" class="btn btn-success">Create Menu</button>
          </div>
        </form>
        {% endif %}
        
      </div>
    </div>
  </div>

</div>

<!-- table filter js -->
<script src="{% static 'js/table-filter.js' %}"></script>

<!-- ajax js -->
<script src="{% static 'js/create_menu.js' %}">
</script>

<!-- continue -->
<script>
  $(document).on("click", "#show", function show () {
    $("#show").hide();
    $("form").removeClass('invisible').addClass('visible');
  });
</script>
{% endblock%}

orderio/templates/menu/update_menu.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
{{menu.get_day_name}} Menu Edit
{% endblock title %}
{% block content %}

<div class="container-fluid">
  <a href="{% url 'menu:weekly_menu' %}">BACK</a>
  <!-- meal choosing -->
  <div class="row " >
    {% for message in messages %}
<div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
    <div class="col-lg-8 col-md-8  card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">You are editing menu for {{menu.get_day_name}}</h6>
      </div>
      <div class="table-responsive" >

        
        <table class="table table-bordered" id="dataTable">
          <thead>
            <tr class="bg-dark text-white">
              <th>Meal</th>
              <th>Calories</th>
              <th>Price</th>
              <th>Description</th>
              <th>Category</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for meal in meals %}
            {% if meal not in menu_meals %}
            <tr>
              <td><a href="{{meal.get_absolute_url}}">{{meal.name}}</a></td>
              <td>{{meal.calories}} </td>
              <td>{{meal.price}} </td>
              <td>{{meal.description|truncatechars:50}}</td>
              <td>{{meal.category.name}}</td>
              <td>
                {% if item_count < 100 %}
                
                <a class="btn btn-primary" href="{% url 'menu:add_to_menu' meal.pk menu.pk %}">Add</a>

                {% else %}
                <button class="btn btn-primary disabled" >Add</button>
                {% endif %}
              </td>
            </tr>
            {% endif %}
            {% endfor %}
          </tbody>
        </table>

      </div>
    </div>


    
    <div  class="col-md-4 col-lg-4 col-sm-12 order-md-last">
      <div id="menu-items">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-primary">Your menu</span>
        
        <span class="badge bg-primary rounded-pill">{{item_count}}</span>
      </h4>
      
      <ul class="list-group mb-3">
        {% if item_count == menu_cap %}
            
        <div class="alert alert-danger">Menu is at maximum capacity!</div>
        {% endif %}
        {% for meal in menu_meals %}
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">{{meal.name}}</h6>
            <small class="text-muted">{{meal.description|truncatechars:30}}</small>
          </div>
          <span class="text-muted">${{meal.price}} 
            <a href="{% url 'menu:remove_from_menu' meal.pk menu.pk %}">
            <i class="bi bi-x-lg text-danger"></i>
            </a>
          </button></span>
          
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
          <span>Menu total price (USD)</span>
          <strong>${{item_price_total}}</strong>
        </li>
      </ul>
      

      <form class="card p-2" action="" method="post" >
        {% csrf_token %}
        <div class="input-group">
          <label for="avability" class="form-control">Avability (Hours)</label>
          <input type="number" class="form-control" placeholder="Avability" name="avability" value="{{menu.avability}}">
          <button type="submit" class="btn btn-success">Save</button>
        </div>
      </form>
    </div>
    </div>
  </div>

</div>

<!-- table filter js -->
<script src="{% static 'js/table-filter.js' %}"></script>

{% endblock content %}

orderio/templates/menu/weekly_menu.html
{% extends "../manager-base.html" %}
{% load static %}
{% block title %}
This week's menu
{% endblock title %}
{% block content %}
{% for message in messages %}
<div class="alert alert-{{message.level_tag}}  alert-dismissible fade show">
  {{message}}
  <small><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></small>
</div>
{% endfor %}
<div class="container-fluid">
  <h1 class="h3 mb-2 text-gray-800">Menus for this week</h1>
  <p class="mb-4">Create,update,delete or approve the menus for this week here.<br>
  <b>Be careful!</b> <br>
  You <i>cannot</i> change the menu after it has been approved.</p>
 
<div class="row">
{% for menu in menus %}

  <div class="col-lg-4 col-md-6">
<div class="card shadow mb-4 ">
  <!-- Card Header - Accordion -->
  <a href="#collapseCardExample{{menu.id}}" class="d-block card-header py-3" data-toggle="collapse"
      role="button" aria-expanded="true" aria-controls="collapseCardExample{{menu.id}}">
      <h6 class="m-0 font-weight-bold text-primary">{{menu.get_day_name}}</h6>
  </a>
  <!-- Card Content - Collapse -->
  <div class="collapse show" id="collapseCardExample{{menu.id}}">
      <div class="card-body">
        Meals:
        {% for meal in menu.meals.all %}
        <li><a href="{{meal.get_absolute_url}}">{{meal.name}}</a></li>
        {% endfor %}
        <div class="my-2">Available for <span class="text-info fw-bold">{{menu.avability}} {% if menu.avability > 1 %}hours{% else %}hour{% endif %}</span> after it is approved.</div> 
        <hr>
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
         
          {% if menu.approved %}
  <button href="#" class="btn btn-success btn-icon-split  btn-sm disabled">
    <span class="icon text-white-50">
      <i class="fas fa-check"></i>
  </span>
  <span class="text">Approved</span></button>
  {%else%}
  <a href="{% url 'menu:update_menu' menu.pk %}" class="btn btn-info btn-sm btn-icon-split">
    <span class="icon text-white-50">
      <i class="far fa-edit"></i>
  </span>
  <span class="text">Edit</span></button>
    
  </a>
  <button  data-url="{% url 'menu:delete_menu' menu.pk %}" data-bs-toggle="modal" data-bs-target="#deleteModal"
   value="{% url 'menu:delete_menu' menu.pk %}" id="del-btn{{menu.pk}}"  class="btn btn-danger btn-icon-split btn-sm mx-1"><span class="icon text-white-50">
    <i class="fas fa-trash"></i>
</span>
<span class="text">Delete</span></button>
    
  {% if menu.meals.all.count > 0 %}
  <button data-url="{% url 'menu:approve_menu' menu.pk %}" value="{% url 'menu:approve_menu' menu.pk %}" class="btn btn-warning btn-icon-split btn-sm" id="approve-btn{{menu.pk}}"  data-bs-toggle="modal" data-bs-target="#approveModal">
    <span class="icon text-white-50">
      <i class="fas fa-check"></i>
  </span>
  <span class="text">Approve</span></button>
  </button>
  {% endif %}
  {% endif %}
        </div>
      </div>
  </div>
</div>
</div>


{% endfor %}
</div>
</div>
<a href="{% url 'menu:create_menu' weekly_menu.pk %}" class="btn btn-primary {% if weekly_menu.menu_set.all.count == 7 %} disabled {% endif %} ">Create</a> 

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">You are about to delete a menu!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to <b class="text-danger">delete</b> this menu?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="conf-btn">Delete</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="approveModal" tabindex="-1" aria-labelledby="approveModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="approveModalLabel">You are about to approve a menu!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to <span class="text-warning">approve</span> this menu?<br>
        <hr>
        <b class="text-danger">Be careful!</b><br> 
        Once you approve the menu, <b><i>you cannot edit or delete it anymore</i></b>!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-warning" id="conf-btn">Approve</button>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/danger-confirmation.js' %}"></script>

{% endblock content %}